### ISSUE TITLE
1.4.2 not starting

### ISSUE THREAD

**Issue by buchanan-fh** [pavsa/hackrf-spectrum-analyzer#15]
Hello,

Windows 10 x64, Java 8 update 181

When running hackrf_sweep_spectrum_analyzer.exe, I get "This application requires a Java Runtime Environment 1.8.0 (64-bit)"

When running the .jar file directly from command line, I get the following
![error_sweep](https://user-images.githubusercontent.com/11913405/43991651-0ba5eb64-9d72-11e8-805e-e29a2f56c2fb.png)

It seems it is looking for a win32-x86 folder ? Although the only existing folder in the application main folder is win32-x86-64

**Comment by pavsa** [comment]
It's because you are using 32bit java runtime, so it is loading 32bit native library, which is not there. Please install 64bit JRE.

**Comment by pavsa** [comment]
no problem :)
