### ISSUE TITLE
FFT Bin below 5000hz disconnects HackRF

### ISSUE THREAD

**Issue by Drackonic** [pavsa/hackrf-spectrum-analyzer#36]
When I set the FFT bin below 5000hz the HackRF disconnects and will not reconnect until increased to 5000 or higher again. Limits some usefulness when looking at a tighter frequency range.

HackRF One, with latest firmware version. 

Windows 10 64bit version 2004.

**Comment by pavsa** [comment]
>argument error: FFT bin width (-w) must be no less than 2445
This is explained by [[FFT - not supported value](https://github.com/greatscottgadgets/hackrf/blob/master/host/hackrf-tools/src/hackrf_sweep.c#L399)](https://github.com/greatscottgadgets/hackrf/blame/master/host/hackrf-tools/src/hackrf_sweep.c#L672)
Will fix the UI value to have this as minimum
