### ISSUE TITLE
hack rf spectrum analyzer not work after update firmware

### ISSUE THREAD

**Issue by juankr10s** [pavsa/hackrf-spectrum-analyzer#38]
hi,
i have a problem with hack rf spectrum analyzer not work after upgrade firmware
log show this:
![image](https://user-images.githubusercontent.com/45793359/114344517-f8817780-9b2d-11eb-9132-bd842ba4926b.png)

and :
![image](https://user-images.githubusercontent.com/45793359/114344667-3c747c80-9b2e-11eb-8b53-24e81b373571.png)

and screen show this

![image](https://user-images.githubusercontent.com/45793359/114344781-6ded4800-9b2e-11eb-8051-0451c1a5512d.png)

**Comment by Dyserna** [comment]
Can confirm having the same exact issue, upgraded to firmware release v2021.03.1

**Comment by TheMKDev** [comment]
Exact Same issue also on 2021.03.1

**Comment by pavsa** [comment]
> https://github.com/mossmann/hackrf/releases/tag/v2021.03.1
> 
> To upgrade to this release, you must update libhackrf and hackrf-tools on your host computer. You must also update firmware on your HackRF.

Obviously, I have to update the code to the new version. 

I will retain the old version for old firmwares.

**Comment by avian2** [comment]
I anyone here is interested, the commit linked above fixes this problem for me. However, I didn't retain backwards compatibility with older firmware versions.
