### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by or-dos** [pavsa/hackrf-spectrum-analyzer#52]
Kali GNU/Linux Rolling
Got this error:
~/hackrf-spectrum-analyzer/src/hackrf-sweep]
└─$ make                                                           
# format the src # clang-format --style=file:../../../.clang-format -i hackrf_sweep.c
(cd lib/hackrf/ && git reset --hard v2023.01.1 && git apply < ../../src-c/0001-hackrf_sweep-to-library-conversion.patch)
fatal: ambiguous argument 'v2023.01.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
make: *** [Makefile:105: patch_hackrf] Error 128

**Comment by muaddib1984** [comment]
I had the same issue. ```git clone --recurse-submodules``` worked for me.
