### ISSUE TITLE
 unknown revision or path not in the working tree. after running make

### ISSUE THREAD

**Issue by sohmee** [pavsa/hackrf-spectrum-analyzer#54]
I am trying to install [hackrf-spectrum-analyzer on ubuntu 22.04
sudo apt install build-essential ant git libusb-1.0 libfftw3-bin libfftw3-dev default-jdk mingw-w64
git clone --depth=1 https://github.com/pavsa/hackrf-spectrum-analyzer.git
cd hackrf-spectrum-analyzer/src/hackrf-sweep/
make

I get the following

format the src # clang-format --style=file:../../../.clang-format -i hackrf_sweep.c
(cd lib/hackrf/ && git reset --hard v2023.01.1 && git apply < ../../src-c/0001-hackrf_sweep-to-library-conversion.patch)
fatal: ambiguous argument 'v2023.01.1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
make: *** [Makefile:105: patch_hackrf] Error 128

Please help.

Thanks

**Comment by sohmee** [comment]
I think this has something to do with the path but how can I fix it?

**Comment by hs1white** [comment]
If you use the --recurse-submodules flag when cloning then it should work:

git clone --recurse-submodules --depth=1 https://github.com/pavsa/hackrf-spectrum-analyzer.git

somebody figured it out here:
https://github.com/pavsa/hackrf-spectrum-analyzer/pull/51/commits/10000e410d6d35d89e8d9d51aa85284fca5d19f5

**Comment by All3xJ** [comment]
> If you use the --recurse-submodules flag when cloning then it should work:
> 
> git clone --recurse-submodules --depth=1 https://github.com/pavsa/hackrf-spectrum-analyzer.git
> 
> somebody figured it out here: [10000e4](https://github.com/pavsa/hackrf-spectrum-analyzer/commit/10000e410d6d35d89e8d9d51aa85284fca5d19f5)

this fixed for me.
