### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Keziolio** [pavsa/hackrf-spectrum-analyzer#7]

**Comment by chudgoo** [comment]
This is what I was using:
https://github.com/xmikos/qspectrumanalyzer
https://github.com/dirkcgrunwald/hackrf-power

**Comment by jamesshao8** [comment]
I have also the requirement to use hackrf_sweep in ubuntu, I tried qspectrumanalyzer, but unfortunately I can't achieve same result as this software did in windows. I mean that qspectrumananlyzer can only show normal spectrum in side the sampling range of hackrf.. can some one help me on this?

**Comment by pavsa** [comment]
I am looking into it.

**Comment by pavsa** [comment]
Pushing a version right now that is tested on ubuntu

**Comment by realAkhmed** [comment]
Don't have HackRF device available right now to test the sweep function but I can report that the code compiles and launches fine on Ubuntu 16.04. 

Needs the following additional libraries + Java stuff
```
sudo apt-get install libfftw3-dev libusb-1.0
```

**Comment by pavsa** [comment]
Yes, I have put the instructions on the main page with the push.

**Comment by Keziolio** [comment]
It's working fine on archlinux, thanks
